# Generated by Django 5.0.5 on 2024-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="User Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="Password")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                ("address", models.TextField(verbose_name="Address")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="recipient_profiles/",
                        verbose_name="Upload Profile",
                    ),
                ),
                (
                    "otp",
                    models.CharField(
                        default="000000",
                        help_text="Enter OTP for verification",
                        max_length=6,
                        verbose_name="OTP",
                    ),
                ),
                (
                    "otp_status",
                    models.CharField(
                        default="Not Verified",
                        help_text="OTP status",
                        max_length=15,
                        verbose_name="OTP Status",
                    ),
                ),
            ],
        ),
    ]
