# Generated by Django 5.0.5 on 2024-05-09 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipientapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full Name"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone_number",
                    models.CharField(max_length=15, verbose_name="Phone Number"),
                ),
                (
                    "organs_needed",
                    models.CharField(max_length=500, verbose_name="Organs Needed"),
                ),
                (
                    "urgency_level",
                    models.CharField(
                        choices=[
                            ("high", "High - Immediate"),
                            ("medium", "Medium - Within 6 months"),
                            ("low", "Low - Routine"),
                        ],
                        max_length=10,
                        verbose_name="Urgency Level",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organ_requests",
                        to="recipientapp.recipient",
                        verbose_name="Recipient",
                    ),
                ),
            ],
        ),
    ]
