# Generated by Django 5.0.5 on 2024-05-10 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donorapp", "0004_donation_hospital_status"),
        ("recipientapp", "0002_organrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="organrequest",
            name="linked_donation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="donorapp.donation",
                verbose_name="Linked Donation",
            ),
        ),
        migrations.AddField(
            model_name="organrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending - Request Submitted"),
                    ("matched", "Matched - Donor Found"),
                    ("completed", "Completed - Transplant Successful"),
                ],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
