# Generated by Django 5.0.5 on 2024-05-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipientapp", "0003_organrequest_linked_donation_organrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organrequest",
            name="status",
            field=models.CharField(
                choices=[
                    (
                        "pending",
                        "Request Submitted. The recipient is waiting for a donor.",
                    ),
                    (
                        "matched",
                        "Donor Found. A suitable donor has been found for the recipient.",
                    ),
                    (
                        "completed",
                        "Transplant Successful. The organ transplant was successful.",
                    ),
                ],
                default="pending",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
