# Generated by Django 5.0.5 on 2024-05-11 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0001_initial"),
        ("recipientapp", "0005_organtransactiondetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="organtransactiondetail",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hospital_transactions",
                to="hospitalapp.hospital",
            ),
        ),
    ]
