# Generated by Django 5.0.5 on 2024-05-11 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipientapp", "0007_organrequest_hospital"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganTransactionDetail",
        ),
    ]
