# Generated by Django 5.0.5 on 2024-05-11 12:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospitalapp", "0001_initial"),
        ("recipientapp", "0008_delete_organtransactiondetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganTransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=64)),
                ("sender_address", models.CharField(max_length=42)),
                ("contract_address", models.CharField(max_length=42)),
                ("gas_used", models.BigIntegerField()),
                ("block_number", models.BigIntegerField()),
                ("gas_limit", models.BigIntegerField()),
                ("mined_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("block_hash", models.CharField(max_length=64)),
                ("value", models.BigIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospital_transactions",
                        to="hospitalapp.hospital",
                    ),
                ),
                (
                    "organ_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organ_transaction_details",
                        to="recipientapp.organrequest",
                    ),
                ),
            ],
        ),
    ]
