# Generated by Django 5.0.5 on 2024-05-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donorapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="otp",
            field=models.CharField(
                default="000000", help_text="Enter OTP for verification", max_length=6
            ),
        ),
        migrations.AddField(
            model_name="donor",
            name="otp_status",
            field=models.CharField(
                default="Not Verified", help_text="OTP status", max_length=15
            ),
        ),
    ]
