# Generated by Django 5.0.5 on 2024-05-11 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donorapp", "0005_alter_donation_hospital_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=64)),
                ("sender_address", models.CharField(max_length=42)),
                ("contract_address", models.CharField(max_length=42)),
                ("gas_used", models.BigIntegerField()),
                ("block_number", models.BigIntegerField()),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="donorapp.donation",
                    ),
                ),
            ],
        ),
    ]
