# Generated by Django 5.0.5 on 2024-05-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("donorapp", "0006_transactiondetail"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TransactionDetail",
        ),
    ]
