# Generated by Django 5.0.5 on 2024-05-11 11:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donorapp", "0007_delete_transactiondetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_hash", models.CharField(max_length=64)),
                ("sender_address", models.CharField(max_length=42)),
                ("contract_address", models.CharField(max_length=42)),
                ("gas_used", models.BigIntegerField()),
                ("block_number", models.BigIntegerField()),
                ("gas_limit", models.BigIntegerField()),
                ("mined_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("block_hash", models.CharField(max_length=64)),
                ("value", models.DecimalField(decimal_places=0, max_digits=19)),
                (
                    "donation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="donorapp.donation",
                    ),
                ),
            ],
        ),
    ]
