# Generated by Django 5.0.5 on 2024-05-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donorapp", "0008_transactiondetail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactiondetail",
            name="value",
            field=models.IntegerField(),
        ),
    ]
